FROM remote-docker.artifactory.swisscom.com/python:3.8-alpine

MAINTAINER "Magdalini Zachariadou, Swisscom INI-EOS-OEN"
LABEL org.opencontainers.image.authors="smartautomation.AIFactory@swisscom.com (AI Factory smART Automation, INI-EOS-OEN)"

WORKDIR /opt/nat-pytest

EXPOSE 8000

# Use this for Alpine image
RUN sed -i 's#http.*://dl-cdn.alpinelinux.org/alpine#https://artifactory.swisscom.com/artifactory/alpine-remote#g' /etc/apk/repositories

# Copy all file tree to working directory:
COPY ./ ./

RUN pip config set global.index-url https://artifactory.swisscom.com/artifactory/api/pypi/pypi-remote/simple \
 && pip install --upgrade pip \
 && pip install -r requirements.txt \
    --no-cache

# run tests from within main
CMD ["python","./main.py"]

# run only one specific test
#CMD ["pytest","./tests/test_sysexit.py"]
# following command does the discovery in "tests" folder
#CMD ["pytest"]