#!/bin/sh


PMACCTD_CONF="$1"

# find directory, where this script resides
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# set librdkafka.conf to the file in this script's directory
# define out_schema_folder as the folder, which will receive the dynamically generated by pmacct AVRO files
LIBRDKAFKA_CONF="$SCRIPT_DIR/librdkafka.conf"
OUT_AVRO_SCHEMA_FOLDER="$SCRIPT_DIR/output_schema_folder"
#echo "$SCRIPT_DIR\n$PMACCTD_CONF\n$LIBRDKAFKA_CONF\n$OUT_AVRO_SCHEMA_CONF"

# docker inspect will return 1 if pmacct container already exists
# if so, the pmacct container is removed (before it is deployed next)
docker inspect --format="{{ .State.Running }}" pmacct >/dev/null 2>&1
if [ $? -ne 1 ]; then
  docker rm pmacct
fi

# deploy pmacct container
docker run -v "$PMACCTD_CONF":/etc/pmacct/nfacctd.conf \
           -v "$LIBRDKAFKA_CONF":/etc/pmacct/maps_dev/librdkafka.conf \
           -v "$OUT_AVRO_SCHEMA_FOLDER":/var/log/pmacct/avsc \
           --network pmacct_test_network \
           -p 2929:8989/udp \
           --name pmacct \
           remote-docker.artifactory.swisscom.com/pmacct/nfacctd >/dev/null 2>&1 &
